validatoraddress = "4C098A5D81BBBC13013151527F32BEE9236701CA"
[GenesisDoc]
  GenesisTime = 2018-05-08T09:26:05Z
  ChainName = "BurrowChain_2A0FC2"
  [GenesisDoc.GlobalPermissions]
    Roles = []
    [GenesisDoc.GlobalPermissions.Base]
      Perms = 2302
      SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "4C098A5D81BBBC13013151527F32BEE9236701CA"
    PublicKey = "{\"type\":\"ed25519\",\"data\":\"68EED9B10C8B45F1AE636A92AC300C7A9B0B9036B4B5842AF8E88B85BB802EAB\"}"
    Amount = 99999999999999
    Name = "Full_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 16383
        SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "412F05D7C516A920D577A83BF57EE7468A475187"
    PublicKey = "{\"type\":\"ed25519\",\"data\":\"5B97ECE82846792B3E9F8574307EAFE76A7D552367CB95AA1ADBBA46A469A77F\"}"
    Amount = 9999999999
    Name = "Participant_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 2118
        SetBit = 2118

  [[GenesisDoc.Validators]]
    Address = "4C098A5D81BBBC13013151527F32BEE9236701CA"
    PublicKey = "{\"type\":\"ed25519\",\"data\":\"68EED9B10C8B45F1AE636A92AC300C7A9B0B9036B4B5842AF8E88B85BB802EAB\"}"
    Amount = 9999999999
    Name = "Full_0"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "4C098A5D81BBBC13013151527F32BEE9236701CA"
      PublicKey = "{\"type\":\"ed25519\",\"data\":\"68EED9B10C8B45F1AE636A92AC300C7A9B0B9036B4B5842AF8E88B85BB802EAB\"}"
      Amount = 9999999999

[Tendermint]
  Seeds = ""
  ListenAddress = "tcp://0.0.0.0:46656"
  Moniker = ""
  TendermintRoot = ".burrow"

[Keys]
  URL = "http://localhost:4767"

[RPC]
  [RPC.V0]
    Disabled = false
    [RPC.V0.Server]
      ChainId = ""
      [RPC.V0.Server.bind]
        address = "localhost"
        port = 1337
      [RPC.V0.Server.TLS]
        tls = false
        cert_path = ""
        key_path = ""
      [RPC.V0.Server.CORS]
        enable = false
        allow_credentials = false
        max_age = 0
      [RPC.V0.Server.HTTP]
        json_rpc_endpoint = "/rpc"
      [RPC.V0.Server.web_socket]
        websocket_endpoint = "/socketrpc"
        max_websocket_sessions = 50
        read_buffer_size = 4096
        write_buffer_size = 4096
  [RPC.TM]
    Disabled = false
    ListenAddress = "tcp://localhost:46657"
  [RPC.Profiler]
    Disabled = true
    ListenAddress = "tcp://localhost:6060"

[Logging]
  ExcludeTrace = false
  NonBlocking = false
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
      Format = "json"
